### ISSUE TITLE
the method 'getfirstimage' does not exist on 'Page'

### ISSUE THREAD

**Issue by spekulatius** [toastnz/open-graph-meta#5]
Hello @danaenz 

thanks for the upgrade. I noticed an error after the upgrade:

    [User Error] Uncaught Exception: Object->__call(): the method 'getfirstimage' does not exist on 'Page', or the method is not public.

I couldn't find the method in the code base or SilverStripe framework/cms. Should that actually have been a method in the module?

Peter

**Comment by danaenz** [comment]
Hi @spekulatius 

Sorry about that - I've pushed an update that fixes the issue 3a1b684
